apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petclinic-git
spec:
  type: git
  params:
  - name: url
    value: https://gogs-peter-cicd-tools.apps.ocpcluster.peterho.internal/gogs/spring-petclinic.git
  - name: depth
    value: "0"
  - name: sslVerify
    value: 'false'