apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petclinic-config-git
spec:
  type: git
  params:
  - name: url
    value: https://gogs-peter-cicd-tools.apps.ocpcluster.peterho.internal/gogs/spring-petclinic-config.git
  - name: sslVerify
    value: 'false'